---
title: Análisis de datos de covid-19 de Costa Rica mediante funciones del paquete
  base de R
author: "Pedro Báez Marín"
date: '2022-05-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación 
Este documento presenta gráficos generados a partir de los datos de COVID-19 en Costa Rica compartidos por el Ministerio de Salud en [https://geovision.uned.ac.cr/oges/
](https://geovision.uned.ac.cr/oges/
)

## Entradas

```{r carga-datos}
covid <- read.csv(file = "05_10_22_CSV_GENERAL.csv", sep = ";")
```


## Procesamiento

## Opciones generales

```{r opciones-generales}
options(scipen = 7)

```


### Curación de datos

```{r}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")

```


## Salidas



### Gráficos



#### Casos acumulados 



##### Positivos

```{r casos-positivos-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  main = "Casos acumulados positivos de COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos"
)
```


